### PR TITLE
feat: Improve types for composite roles

### LINKED ISSUE #741: Show typescript autocompletion for `role` prop in components
I was thinking that since we are showing warnings for invalid `role` prop in the Composite component we can also enforce the types as well, this way users would get autocompletion for the valid role values.

https://github.com/reakit/reakit/blob/6f6d1ad9177156cafa4adf9c987a43c79a1bbb90/packages/reakit/src/Composite/Composite.ts#L47-L58

We can change it so that users would get the autocompletion

```ts

const validCompositeRoles = [
  "combobox",
  "grid",
  "tablist",
  "listbox",
  "menu",
  "menubar",
  "toolbar",
  "radiogroup",
  "tree",
  "treegrid",
] as const;

type CompositeRoles = typeof validCompositeRoles[number];

export type CompositeOptions = TabbableOptions &
  Pick<
    Partial<CompositeStateReturn>,
    | "baseId"
    | "unstable_virtual"
    | "currentId"
    | "orientation"
    | "unstable_moves"
    | "wrap"
    | "groups"
  > &
  Pick<
    CompositeStateReturn,
    "items" | "setCurrentId" | "first" | "last" | "move"
  > & { role?: CompositeRoles };
```

reakit-autocomplete

### PR DESCRIPTION
**Pull request by anuraghazra**
Closes #741

### CODE REVIEW

**Comment by anuraghazra** [comment]
Hi @diegohaz i've done the changes, but for some reason the tests are failing in my local machine 🤔 i pushed anyways hoping you could help me fix it. 

The test are failing with

```js
Expected mock function not to be called but it was called with:
    ["You should provide a valid `role` attribute to composite components.", "
    ", "See https://reakit.io/docs/composite"]
```

but  the role prop is provided 🤔

**Comment by anuraghazra** [comment]
Ahh look at the typecheck error. seems like this should not be "button" right? 

```js
##[error]packages/reakit/src/Composite/__tests__/index-test.tsx(51,37): error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: BoxOptions & { disabled?: boolean | undefined; focusable?: boolean | undefined; } & Pick<Partial<CompositeStateReturn>, "wrap" | ... 5 more ... | "unstable_moves"> & ... 4 more ... & { ...; }): Element', gave the following error.
    Type '"button"' is not assignable to type '"menu" | "listbox" | "grid" | "menubar" | "toolbar" | "tree" | "combobox" | "tablist" | "radiogroup" | "treegrid" | undefined'.
```

**Comment by diegohaz** [comment]
I think you have to add a `// @ts-expect-error` on this test: https://github.com/reakit/reakit/blob/6f6d1ad9177156cafa4adf9c987a43c79a1bbb90/packages/reakit/src/Composite/__tests__/index-test.tsx#L47-L60

**Comment by diegohaz** [comment]
The tests are failing because now `role` is coming from `options`, not from `htmlProps`, and therefore it's not being passed down from the hook to the element. It must be explicitly passed.

**Comment by anuraghazra** [comment]
Oh yup! right.

**Comment by anuraghazra** [comment]
These are some pretty cool infra scripts you have setup! haha nice!

**Review by diegohaz — APPROVED** [review]
Awesome! Thanks @anuraghazra!

**Comment by diegohaz** [comment]
Oh, after merging it into the next branch and checking the [failed tests](https://github.com/reakit/reakit/runs/1129795306#step:11:6) I realized that this is actually a breaking change for people who rely on `React.HTMLAttributes` or `GridHTMLProps` instead of `GridProps`.

I'll revert the commit for now. But it would be cool if we could get the autocomplete without restricting the types.

**Comment by anuraghazra** [comment]
Oh opps! okay i will checkout to next branch and see if i can find a workaround. 👍

**Comment by tom-sherman** [comment]
I don't think you can have both autocompletion from a string union and accept any string because TypeScript will automatically simplify `'a' | 'b' | string` to just `string`.

The workaround I can think of is to have an enum (or enum-like object) exported by the library so that users can kind of opt in. It's not ideal though and I'd personally be hesitant to add what is basically a whole new pattern for a single component's prop - especially since most users aren't going to take advantage of it because it would be opt in.

**Comment by diegohaz** [comment]
There's a hack for that. But is it worth it?

TypeScript repl screenshot. Text version on the link below.

https://www.typescriptlang.org/play?#code/C4TwDgpgBA6hCWAnAJgZWI+A7A5lAvFAM4bZ4BkUA3lAPrw5YD2iEtAthAPwBcUAhlhBQAvgG4AUKEhQAqlnhMsBKACJ+qqAB81AI007VAYwOwEKdJlySJAMwCuWI8EXL+ACgBu-ADb2IfPKuAJTUIhISHqrIqsGSUbFAA

**Comment by anuraghazra** [comment]
Wow Haz, I did tried everything but nothing worked, but this is 🤯 
Atleast learned something new ❤️

**Comment by anuraghazra** [comment]
Okay i also have a workaround.

image



https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgSwPZygXigIgIaagHywCM9CBlYAJwTgHMBuAKEYGMUBnYKAMQFc4W6KAAowlJGHYAuWIhQBKdAD4oAb0ZQolCMF6VUeOLwA2xzEwC+TRnwHDMmeddst7ueUA
